import { Buffer } from "node:buffer";
import { randomUUID } from "node:crypto";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { NextResponse } from "next/server";
import {
  buildImageAssetProfile,
  buildReferenceVideoAssetProfile,
  writeAssetProfilesDebug
} from "@/lib/asset-builder";
import { generateFalKlingVideo } from "@/lib/fal-kling";
import { saveCreatorImage, saveOutputBuffer, saveProductImage, saveUpload } from "@/lib/files";
import { analyzeReferenceVideo } from "@/lib/gemini";
import { buildAssetBindingDebug, resolveGenerationIntent, writeIntentDebug } from "@/lib/intent-resolver";
import { createProductFocusPlans } from "@/lib/planner";
import { createQualityStarterImage } from "@/lib/quality-starter";
import { hasR2Config, publicGlobalObjectKey, publicObjectKey, readPublicObject, uploadPublicObject } from "@/lib/r2";
import { legacyPublicOutputCandidatePath, runtimeOutputCandidatePath, runtimeOutputUrl } from "@/lib/runtime-storage";
import { createReferenceStarterFrame } from "@/lib/scene-starter";
import type { AssetProfile, GeneratedVideo, InputSnapshot, PipelineResult, ProductFocusInput } from "@/lib/types";
import { getVideoFormat, getVideoSubFormat } from "@/lib/video-formats";

export const runtime = "nodejs";
export const maxDuration = 300;

const validDurations = new Set([5, 10, 15]);
const logsDir = process.env.VERCEL
  ? path.join("/tmp", "ugclabs", "logs")
  : path.join(process.cwd(), "logs");
const historyIndexPath = path.join(logsDir, "history-index.json");
const outputDir = path.join(process.cwd(), "public", "outputs");

type CreatorReference = {
  accountName: string;
  imagePath?: string;
  imageMimeType?: string;
  assetProfile?: AssetProfile;
};

type StarterPreviewContext = {
  jobId: string;
  input: ProductFocusInput;
  referenceVideo?: File;
  productImage: File;
  creatorReferences: CreatorReference[];
};

type ProjectHistoryEntry = {
  jobId: string;
  title: string;
  createdAt: string;
  formatName: string;
  styleName: string;
  videoCount: number;
  thumbnailUrl?: string;
};

export async function POST(request: Request) {
  let jobId = randomUUID().slice(0, 8);

  try {
    const form = await request.formData();
    jobId = parseJobId(form.get("clientJobId")) ?? jobId;
    const runMode = String(form.get("runMode") || "video");
    const referenceVideo = form.get("referenceVideo");
    const input = parseInput(form);
    const productImage = productImageFromForm(form.get("productImage"), form, input.productName);
    const usableReferenceVideo = referenceVideo instanceof File && referenceVideo.size > 0
      ? referenceVideo
      : undefined;

    if (input.generationMode !== "fast_ugc" && !usableReferenceVideo) {
      return NextResponse.json({ error: "referenceVideo is required." }, { status: 400 });
    }

    if (!productImage) {
      return NextResponse.json({ error: "productImage is required." }, { status: 400 });
    }

    if (runMode !== "starter" && !hasFalApiKey()) {
      return NextResponse.json(
        { error: "FAL_KEY or FAL_API_KEY is required for fal Kling v3 Pro Image-to-Video generation." },
        { status: 400 }
      );
    }

    input.productImageProvided = true;

    const creatorReferences = await saveCreatorReferences(form, jobId, input);
    input.creatorReferenceProvided = creatorReferences.some((reference) => Boolean(reference.imagePath));

    if (input.modelMode !== "auto_generated" && !input.creatorReferenceProvided) {
      return NextResponse.json(
        { error: "Model reference mode requires a creator image upload." },
        { status: 400 }
      );
    }

    if (
      input.modelMode === "per_account_models"
      && creatorReferences.some((reference) => !reference.imagePath)
    ) {
      return NextResponse.json(
        { error: "Per-account model mode requires one model image for each account." },
        { status: 400 }
      );
    }

    if (runMode === "starter") {
      return createStarterPreviewResponse({
        jobId,
        input,
        referenceVideo: usableReferenceVideo,
        productImage,
        creatorReferences
      });
    }

    const warnings: string[] = [
      "Video engine: fal Kling v3 Pro Image-to-Video.",
      generationModeWarning(input),
      "Native audio is generated by fal Kling with generate_audio=true.",
      input.referenceProductMode === "same_product"
        ? "Product source mode: same product. Reference product handling is preserved when it matches the uploaded product image."
        : "Product source mode: replace product. Reference video structure is reused, but uploaded product image/use plan defines the target product.",
      modelModeWarning(input)
    ];

    const productImagePath = await saveProductImage(productImage, jobId);
    const referenceVideoPath = usableReferenceVideo
      ? await saveUpload(usableReferenceVideo, jobId)
      : undefined;
    const approvedStarterJobId = parseJobId(form.get("approvedStarterJobId"));
    const starterImagePath = input.creatorReferenceProvided
      ? await getApprovedQualityStarterPath(approvedStarterJobId)
      : referenceVideoPath
        ? await createReferenceStarterFrame(referenceVideoPath, jobId, warnings)
        : undefined;

    if (input.creatorReferenceProvided && !starterImagePath) {
      return NextResponse.json(
        { error: "Model reference generation requires an approved starter image first." },
        { status: 400 }
      );
    }

    if (input.creatorReferenceProvided && starterImagePath) {
      warnings.push(
        "Scene starter: using approved quality starter image as start_image_url for model/product/reference composition."
      );
    }

    const referenceVideoAssetProfile = referenceVideoPath && usableReferenceVideo
      ? await buildReferenceVideoAssetProfile({
          filePath: referenceVideoPath,
          mimeType: usableReferenceVideo.type || "video/mp4",
          label: usableReferenceVideo.name || "Reference video"
        })
      : undefined;
    const productAssetProfile = await buildImageAssetProfile({
      kind: "product",
      filePath: productImagePath,
      mimeType: productImage.type || "image/png",
      label: input.productName,
      userGuidance: input.productFeatureNotes,
      analysisMode: input.productAnalysisMode
    });
    const profiledCreatorReferences = await buildCreatorAssetProfiles(creatorReferences);

    input.referenceVideoAssetProfile = referenceVideoAssetProfile;
    input.productAssetProfile = productAssetProfile;
    input.creatorAssetProfile = profiledCreatorReferences.find((reference) => reference.assetProfile)?.assetProfile;

    await writeAssetProfilesDebug(jobId, [
      referenceVideoAssetProfile,
      productAssetProfile,
      ...profiledCreatorReferences
        .map((reference) => reference.assetProfile)
        .filter((profile): profile is AssetProfile => Boolean(profile))
    ]);

    if (referenceVideoAssetProfile) {
      warnings.push(...assetProfileWarnings("Reference video", referenceVideoAssetProfile));
    }
    warnings.push(...assetProfileWarnings("Product", productAssetProfile));
    const tryOnCompatibility = validateTryOnCompatibility(input, productAssetProfile);
    warnings.push(...tryOnCompatibility.warnings);
    if (!tryOnCompatibility.ok) {
      return NextResponse.json(
        { error: tryOnCompatibility.message, warnings: dedupe(warnings) },
        { status: 400 }
      );
    }
    for (const reference of profiledCreatorReferences) {
      if (reference.assetProfile) {
        warnings.push(...assetProfileWarnings(`Model ${reference.accountName}`, reference.assetProfile));
      }
    }

    const analysis = referenceVideoPath && usableReferenceVideo
      ? await analyzeReferenceVideo(referenceVideoPath, usableReferenceVideo.type || "video/mp4", input)
      : buildFastUgcReferenceAnalysis(input);
    const intent = resolveGenerationIntent(input, analysis);
    const assetBinding = buildAssetBindingDebug(input);
    await writeIntentDebug(jobId, intent);
    warnings.push(`Intent resolver: ${intent.productMode.label} / ${intent.videoFormat.name}.`);
    warnings.push("Prompt composer: GPT creates Product Selling Plan and fal Kling generationPrompt from Gemini/Product/Avatar analysis.");

    const plans = await createProductFocusPlans(analysis, input, intent);
    const selectedPlans = plans.slice(0, input.count);
    const videos: GeneratedVideo[] = [];

    for (const plan of selectedPlans) {
      const creatorReference = pickCreatorReference(profiledCreatorReferences, plan.index);

      try {
        const sourceUrl = await generateFalKlingVideo(
          plan.generationPrompt,
          input.duration,
          {
            productImagePath,
            productImageMimeType: productImage.type || "image/png",
            creatorImagePath: creatorReference?.imagePath,
            creatorImageMimeType: creatorReference?.imageMimeType,
            starterImagePath,
            starterImageMimeType: starterImagePath ? mimeTypeFromPath(starterImagePath) : undefined
          },
          {
            generateAudio: true,
            warnings,
            debug: { jobId, index: plan.index }
          }
        );
        const playbackUrl = await persistRemoteVideo(jobId, plan.index, sourceUrl, "fal-kling", warnings);

        videos.push({
          index: plan.index,
          accountName: creatorReference?.accountName,
          hook: plan.hook,
          script: plan.voiceoverScript,
          generationPrompt: plan.generationPrompt,
          playbackUrl: playbackUrl ?? sourceUrl,
          sourceUrl,
          audioMode: "native_audio",
          status: "completed"
        });
      } catch (error) {
        videos.push({
          index: plan.index,
          accountName: creatorReference?.accountName,
          hook: plan.hook,
          script: plan.voiceoverScript,
          generationPrompt: plan.generationPrompt,
          status: "failed",
          error: error instanceof Error ? error.message : "Unknown generation error"
        });
      }
    }

    const createdAt = new Date().toISOString();
    const payload: PipelineResult = {
      jobId,
      inputSnapshot: buildInputSnapshot(input, {
        createdAt,
        productImage,
        referenceVideo: usableReferenceVideo,
        creatorReferences: profiledCreatorReferences,
        approvedStarterJobId
      }),
      analysis,
      intent,
      assetBinding,
      assetProfiles: {
        referenceVideo: referenceVideoAssetProfile,
        product: productAssetProfile,
        creator: input.creatorAssetProfile
      },
      videos,
      warnings: dedupe(warnings)
    };

    await writePipelineResult(payload);
    await writeHistoryEntry({
      jobId,
      title: input.productName || "Untitled product",
      createdAt,
      formatName: input.subFormatName ?? getVideoFormat(input.videoFormat).name,
      styleName: input.generationMode === "fast_ugc"
        ? "Fast UGC"
        : input.generationMode === "reference_match"
          ? "Reference Match"
          : "Winning Ad Remix",
      videoCount: videos.length,
      thumbnailUrl: videos.find((video) => video.playbackUrl || video.sourceUrl)?.playbackUrl
        ?? videos.find((video) => video.playbackUrl || video.sourceUrl)?.sourceUrl
    });
    return NextResponse.json(payload);
  } catch (error) {
    await writeApiErrorDebug(jobId, "POST /api/product-focus/generate", error);
    return NextResponse.json(
      {
        error: error instanceof Error ? error.message : "Generation failed."
      },
      { status: 500 }
    );
  }
}

export async function GET(request: Request) {
  const url = new URL(request.url);
  const jobId = parseJobId(url.searchParams.get("jobId"));

  if (!jobId) {
    return NextResponse.json({ error: "jobId is required." }, { status: 400 });
  }

  const payload = await readPipelineResult(jobId);

  if (!payload) {
    return NextResponse.json({ error: "Result is not ready yet." }, { status: 404 });
  }

  return NextResponse.json(payload);
}

async function writeApiErrorDebug(jobId: string, scope: string, error: unknown): Promise<void> {
  try {
    await mkdir(logsDir, { recursive: true });
    await writeFile(
      path.join(logsDir, `api-error-${jobId}.json`),
      JSON.stringify({
        jobId,
        scope,
        at: new Date().toISOString(),
        error: error instanceof Error
          ? {
              name: error.name,
              message: error.message,
              stack: error.stack
            }
          : error
      }, null, 2),
      "utf8"
    );
  } catch {
    // Preserve the original API failure; diagnostics must not mask it.
  }
}

async function createStarterPreviewResponse(context: StarterPreviewContext) {
  const warnings: string[] = [
    "Quality gate: generated starter preview only. No fal Kling video generation was run."
  ];
  const productImagePath = await saveProductImage(context.productImage, context.jobId);
    const productAssetProfile = await buildImageAssetProfile({
      kind: "product",
      filePath: productImagePath,
      mimeType: context.productImage.type || "image/png",
      label: context.input.productName,
      userGuidance: context.input.productFeatureNotes,
      analysisMode: context.input.productAnalysisMode
    });
  context.input.productAssetProfile = productAssetProfile;
  warnings.push(...assetProfileWarnings("Product", productAssetProfile));

  const tryOnCompatibility = validateTryOnCompatibility(context.input, productAssetProfile);
  if (!tryOnCompatibility.ok) {
    return NextResponse.json(
      {
        error: tryOnCompatibility.message,
        warnings: [...warnings, ...tryOnCompatibility.warnings]
      },
      { status: 400 }
    );
  }

  const referenceVideoPath = context.referenceVideo
    ? await saveUpload(context.referenceVideo, context.jobId)
    : undefined;
  const referenceFramePath = referenceVideoPath
    ? await createReferenceStarterFrame(referenceVideoPath, context.jobId, warnings)
    : undefined;

  if (context.input.generationMode !== "fast_ugc" && !referenceFramePath) {
    return NextResponse.json(
      { error: "Could not extract a reference-video starter frame." },
      { status: 500 }
    );
  }

  const creatorReference = pickCreatorReference(context.creatorReferences, 1);

  if (!creatorReference?.imagePath) {
    return NextResponse.json({
      jobId: context.jobId,
      starterImageUrl: referenceFramePath
        ? runtimeOutputUrl(`${context.jobId}-reference-starter.jpg`)
        : "",
      warnings: [
        ...warnings,
        referenceFramePath
          ? "No model image was provided, so the extracted reference frame is the starter preview."
          : "No model image or reference video was provided, so no starter preview is required."
      ]
    });
  }

  if (!process.env.OPENAI_API_KEY) {
    return NextResponse.json(
      { error: "OPENAI_API_KEY is required to create a model/product quality starter image." },
      { status: 400 }
    );
  }

  const starter = await createQualityStarterImage({
    jobId: context.jobId,
    referenceFramePath,
    productImagePath,
    productImageMimeType: context.productImage.type || "image/png",
    creatorImagePath: creatorReference.imagePath,
    creatorImageMimeType: creatorReference.imageMimeType || "image/png",
    productName: context.input.productName,
    productAssetProfile,
    generationMode: context.input.generationMode,
    videoFormatId: context.input.videoFormat,
    videoFormatName: getVideoFormat(context.input.videoFormat).name
  });

  return NextResponse.json({
    jobId: context.jobId,
    starterImageUrl: starter.localUrl,
    referenceFrameUrl: referenceFramePath ? runtimeOutputUrl(`${context.jobId}-reference-starter.jpg`) : undefined,
    warnings: [
      ...warnings,
      "Quality gate: starter image combines uploaded model identity, uploaded product, Product Use Director placement, and reference-video scene composition."
    ]
  });
}

function parseInput(form: FormData): ProductFocusInput {
  const productName = String(form.get("productName") || "").trim();
  const productUrl = String(form.get("productUrl") || "").trim();
  const productFeatureNotes = englishOnlyText(String(form.get("productFeatureNotes") || "")).trim();
  const productAnalysisMode = productFeatureNotes
    ? "guided"
    : String(form.get("productAnalysisMode") || "auto") === "guided"
      ? "guided"
      : "auto";
  const tone = String(form.get("tone") || "TikTok native").trim();
  const generationMode = parseGenerationMode(String(form.get("generationMode") || "fast_ugc"));
  const requestedSubFormat = getVideoSubFormat(String(form.get("subFormatId") || ""));
  const videoFormat = getVideoFormat(String(form.get("videoFormat") || requestedSubFormat?.videoFormat || "ugc_beauty_product")).id;
  const subFormat = requestedSubFormat?.videoFormat === videoFormat ? requestedSubFormat : undefined;
  const ugcTemplateStyle = parseUgcTemplateStyle(String(form.get("ugcTemplateStyle") || "auto"));
  const modelMode = parseModelMode(String(form.get("modelMode") || "auto_generated"));
  const referenceProductMode = parseReferenceProductMode(String(form.get("referenceProductMode") || "replace_product"));
  const explicitCreatorMode = parseCreatorMode(String(form.get("creatorMode") || "auto"));
  const creatorMode = explicitCreatorMode !== "auto"
    ? explicitCreatorMode
    : modelMode === "auto_generated"
      ? "new_creator"
      : "model_reference";
  const duration = Number(form.get("duration") || 10);
  const count = Math.min(10, Math.max(1, Number(form.get("count") || 3)));

  if (!productName) {
    throw new Error("Product name is required.");
  }

  if (!validDurations.has(duration)) {
    throw new Error("Duration must be 5, 10, or 15 seconds.");
  }

  return {
    generationMode,
    videoFormat,
    subFormatId: subFormat?.id,
    subFormatName: subFormat?.name,
    subFormatIntent: subFormat?.explanation,
    ugcTemplateStyle,
    productName,
    productUrl,
    productFeatureNotes,
    productAnalysisMode,
    productImageProvided: false,
    modelMode,
    creatorMode,
    creatorReferenceProvided: false,
    referenceProductMode,
    audioMode: "native_audio",
    tone,
    duration: duration as 5 | 10 | 15,
    count
  };
}

function buildInputSnapshot(
  input: ProductFocusInput,
  context: {
    createdAt: string;
    productImage?: File;
    referenceVideo?: File;
    creatorReferences: CreatorReference[];
    approvedStarterJobId?: string;
  }
): InputSnapshot {
  return {
    createdAt: context.createdAt,
    generationMode: input.generationMode,
    videoFormat: input.videoFormat,
    subFormatId: input.subFormatId,
    subFormatName: input.subFormatName,
    ugcTemplateStyle: input.ugcTemplateStyle,
    productName: input.productName,
    productUrl: input.productUrl || undefined,
    productFeatureNotes: input.productFeatureNotes || undefined,
    productAnalysisMode: input.productAnalysisMode,
    modelMode: input.modelMode,
    creatorMode: input.creatorMode,
    referenceProductMode: input.referenceProductMode,
    tone: input.tone,
    durationSeconds: input.duration,
    variantCount: input.count,
    productImageProvided: input.productImageProvided,
    productImageFileName: context.productImage?.name || undefined,
    referenceVideoProvided: Boolean(context.referenceVideo),
    referenceVideoFileName: context.referenceVideo?.name || undefined,
    creatorReferenceProvided: input.creatorReferenceProvided,
    creatorReferenceNames: context.creatorReferences
      .filter((reference) => reference.imagePath)
      .map((reference) => reference.accountName),
    approvedStarterJobId: context.approvedStarterJobId
  };
}

function productImageFromForm(
  productImage: FormDataEntryValue | null,
  form: FormData,
  productName: string
): File | undefined {
  if (productImage instanceof File && productImage.size > 0) {
    return productImage;
  }

  const dataUrl = String(form.get("productImageDataUrl") || "");
  const match = dataUrl.match(/^data:([^;,]+);base64,(.+)$/);

  if (!match) return undefined;

  const mimeType = match[1] || "image/png";
  const buffer = Buffer.from(match[2], "base64");

  if (!buffer.length) return undefined;

  return new File([new Uint8Array(buffer)], `${safeAssetName(productName)}.${extensionForMimeType(mimeType)}`, {
    type: mimeType
  });
}

function safeAssetName(value: string) {
  return (value || "saved-product")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    || "saved-product";
}

function extensionForMimeType(mimeType: string) {
  if (mimeType.includes("jpeg") || mimeType.includes("jpg")) return "jpg";
  if (mimeType.includes("webp")) return "webp";
  if (mimeType.includes("gif")) return "gif";
  return "png";
}

function parseUgcTemplateStyle(value: string): string | undefined {
  const normalized = value.trim().toLowerCase();

  if (!normalized || normalized === "auto") {
    return undefined;
  }

  return /^[a-z0-9_-]{2,48}$/.test(normalized) ? normalized : undefined;
}

function englishOnlyText(value: string): string {
  return value.replace(/[^\x20-\x7E]/g, "").replace(/\s{2,}/g, " ");
}

function parseGenerationMode(value: string): ProductFocusInput["generationMode"] {
  if (value === "reference_match" || value === "winning_ad_remix") {
    return value;
  }

  return "fast_ugc";
}

function parseModelMode(value: string): ProductFocusInput["modelMode"] {
  if (value === "shared_model" || value === "per_account_models") {
    return value;
  }

  return "auto_generated";
}

function parseReferenceProductMode(value: string): ProductFocusInput["referenceProductMode"] {
  return value === "same_product" ? "same_product" : "replace_product";
}

function parseCreatorMode(value: string): ProductFocusInput["creatorMode"] {
  if (value === "model_reference" || value === "new_creator" || value === "hand_only") {
    return value;
  }

  return "auto";
}

function parseJobId(value: FormDataEntryValue | string | null): string | undefined {
  if (typeof value !== "string") return undefined;
  const normalized = value.trim().toLowerCase();
  return /^[a-z0-9_-]{6,32}$/.test(normalized) ? normalized : undefined;
}

async function getApprovedQualityStarterPath(jobId: string | undefined): Promise<string | undefined> {
  if (!jobId) return undefined;

  const filename = `${jobId}-quality-starter.png`;
  const starterPath = runtimeOutputCandidatePath(filename);

  try {
    await readFile(starterPath);
    return starterPath;
  } catch {
    const legacyPath = legacyPublicOutputCandidatePath(filename);

    try {
      await readFile(legacyPath);
      return legacyPath;
    } catch {
      return undefined;
    }
  }
}

function hasFalApiKey(): boolean {
  return Boolean(process.env.FAL_KEY || process.env.FAL_API_KEY);
}

async function saveCreatorReferences(
  form: FormData,
  jobId: string,
  input: ProductFocusInput
): Promise<CreatorReference[]> {
  if (input.modelMode === "auto_generated") {
    return [{ accountName: "Auto creator" }];
  }

  if (input.modelMode === "shared_model") {
    const file = firstFile(form, ["sharedCreatorImage", "creatorImage"]);
    return [{
      accountName: String(form.get("sharedModelAccountName") || "All accounts").trim() || "All accounts",
      imagePath: file ? await saveCreatorImage(file, jobId, "creator-shared") : undefined,
      imageMimeType: file?.type || "image/png"
    }];
  }

  const accountCount = Math.min(6, Math.max(1, Number(form.get("modelAccountCount") || 2)));
  const references: CreatorReference[] = [];

  for (let index = 0; index < accountCount; index += 1) {
    const file = firstFile(form, [`accountCreatorImage${index}`]);
    const accountName = String(form.get(`accountName${index}`) || `Account ${index + 1}`).trim()
      || `Account ${index + 1}`;
    references.push({
      accountName,
      imagePath: file ? await saveCreatorImage(file, jobId, `creator-account-${index + 1}`) : undefined,
      imageMimeType: file?.type || "image/png"
    });
  }

  return references;
}

async function buildCreatorAssetProfiles(references: CreatorReference[]): Promise<CreatorReference[]> {
  return Promise.all(
    references.map(async (reference) => {
      if (!reference.imagePath) {
        return reference;
      }

      return {
        ...reference,
        assetProfile: await buildImageAssetProfile({
          kind: "avatar",
          filePath: reference.imagePath,
          mimeType: reference.imageMimeType || "image/png",
          label: reference.accountName
        })
      };
    })
  );
}

function pickCreatorReference(
  references: CreatorReference[],
  planIndex: number
): CreatorReference | undefined {
  const usable = references.filter((reference) => reference.imagePath);
  if (!usable.length) {
    return references[0];
  }

  return usable[(planIndex - 1) % usable.length];
}

function modelModeWarning(input: ProductFocusInput): string {
  if (input.modelMode === "shared_model") {
    return "Model source: one model image is locked for all variants as @Element1.";
  }

  if (input.modelMode === "per_account_models") {
    return "Model source: each account uses its uploaded model image as @Element1.";
  }

  return "Model source: auto creator. No model element is provided, so creator identity may vary.";
}

function generationModeWarning(input: ProductFocusInput): string {
  if (input.generationMode === "fast_ugc") {
    return "Generation mode: Fast UGC. No reference video is required; shot structure is generated from the selected format and product analysis.";
  }

  if (input.generationMode === "winning_ad_remix") {
    return "Generation mode: Winning Ad Remix. Reference video is analyzed for hook, cut order, proof timing, and CTA structure, but is not sent to the video model.";
  }

  return "Generation mode: Reference Match. Reference video is analyzed for style, pacing, framing, gestures, and scene mood, but is not sent to the video model.";
}

function validateTryOnCompatibility(
  input: ProductFocusInput,
  productAssetProfile: AssetProfile
): { ok: boolean; message?: string; warnings: string[] } {
  if (input.videoFormat !== "ugc_virtual_try_on") {
    return { ok: true, warnings: [] };
  }

  const understanding = productAssetProfile.productUnderstanding;
  const physicalUseModel = understanding?.physicalUseModel;
  const haystack = [
    input.productName,
    productAssetProfile.label,
    productAssetProfile.promptNounPhrase,
    productAssetProfile.description,
    understanding?.productType,
    understanding?.productCategory,
    understanding?.primaryUseCase,
    physicalUseModel?.physicalForm,
    physicalUseModel?.interactionModel,
    physicalUseModel?.activationOrAccessPoint,
    physicalUseModel?.outputOrEffectSource,
    physicalUseModel?.plannerDirective,
    ...(understanding?.naturalUseEnvironments ?? []),
    ...(understanding?.typicalUserActions ?? []),
    ...(understanding?.copyAngles ?? []),
    ...(understanding?.allowedActionVerbs ?? []),
    ...(understanding?.proofWords ?? []),
    ...(physicalUseModel?.validInteractionPoints ?? []),
    ...(physicalUseModel?.naturalUseSequence ?? [])
  ].join(" ").toLowerCase();

  const compatiblePattern =
    /\b(apparel|clothing|clothes|garment|outfit|dress|shirt|top|pants|jeans|skirt|jacket|coat|hoodie|sweater|shoe|sneaker|boot|sandal|sock|hat|cap|beanie|eyewear|glasses|sunglasses|contact lens|jewelry|jewellery|earring|necklace|bracelet|ring|watch|bag|purse|handbag|backpack|wearable|accessory|makeup|cosmetic|lipstick|lip gloss|lip tint|foundation|concealer|blush|eyeshadow|mascara|skincare|serum|cream|lotion|sunscreen|cleanser|toner|essence|ampoule|fragrance|perfume|hair|nail|worn|wear|try on|fit|fitting|style|styling|pair|apply|applied|swatch|blend)\b/;
  const incompatiblePattern =
    /\b(toaster|oven|microwave|air fryer|blender|kettle|coffee maker|appliance|furniture|chair|table|sofa|lamp|software|app screen|dashboard|website|platform|saas|screen workflow|phone case|tumbler|cup|mug|bottle|straw|lid|food|snack|tool|device|charger|cable|keyboard|mouse|speaker|countertop|kitchen counter)\b/;

  const compatible = compatiblePattern.test(haystack);
  const incompatible = incompatiblePattern.test(haystack) && !compatible;

  if (compatible && !incompatible) {
    return {
      ok: true,
      warnings: [
        "Fit Director: product appears suitable for UGC Virtual Try On based on Product Analysis / physicalUseModel."
      ]
    };
  }

  return {
    ok: false,
    message:
      "UGC Virtual Try On is only available for wearable, styleable, or applicable products such as apparel, accessories, beauty, skincare, makeup, hair, nail, or fragrance. Use UGC, Tutorial, or Product Only for this product.",
    warnings: [
      "Fit Director: blocked UGC Virtual Try On before paid starter/video generation because Product Analysis did not identify a wearable, styleable, or applicable product.",
      `Fit Director evidence: ${haystack.slice(0, 500)}`
    ]
  };
}

function buildFastUgcReferenceAnalysis(input: ProductFocusInput) {
  const format = getVideoFormat(input.videoFormat);

  return {
    format: input.videoFormat,
    visualStyle: "Native short-form UGC with clear product visibility, natural handheld pacing, and realistic creator energy.",
    sceneSummary: [
      "No reference video was provided. Build a fresh UGC scene from the product analysis, model mode, and selected video format.",
      `Selected format: ${format.name}.`
    ],
    structureSummary:
      "Open with the product visible, show one natural use or proof action, then end with a concise spoken benefit or CTA.",
    motionChoreography: [
      {
        start: "0.0s",
        end: "1.0s",
        cameraDistance: "vertical selfie medium close-up",
        handAction: "bring the uploaded product into clear foreground view",
        faceAction: "creator looks at camera with a quick native hook expression",
        productVisibilityRule: "product must be large and readable in frame",
        mustKeepVisible: ["uploaded product", "creator face when creator mode is active"],
        dialogueBeat: "short hook that names or teases the product benefit"
      },
      {
        start: "1.0s",
        end: `${Math.max(2, input.duration - 1)}.0s`,
        cameraDistance: "handheld close-up or medium product-in-hand shot",
        handAction: "perform one category-correct product proof action",
        faceAction: "natural reaction while keeping attention on the product",
        productVisibilityRule: "keep the product visible while demonstrating the proof detail",
        mustKeepVisible: ["main product shape", "key visible text or design"],
        dialogueBeat: "one concrete benefit line using category-correct words"
      },
      {
        start: `${Math.max(2, input.duration - 1)}.0s`,
        end: `${input.duration}.0s`,
        cameraDistance: "stable ending close-up",
        handAction: "hold product steady for final proof or CTA",
        faceAction: "small satisfied smile or approving nod",
        productVisibilityRule: "end with product still visible",
        mustKeepVisible: ["uploaded product"],
        dialogueBeat: "short CTA or final recommendation"
      }
    ],
    earliestClearProductMoment: "The uploaded product should be clearly visible in the opening frame.",
    bestProductProofShot: "Use one close product detail or usage moment that visually proves the main benefit.",
    productExposureMoments: [
      "0-1s clear product reveal",
      "mid-shot product handling or use",
      "final product close-up or satisfied creator reaction"
    ],
    hookPatterns: [
      "quick native product recommendation",
      "simple problem-to-benefit statement",
      "creator shows the product before explaining it"
    ],
    pacingNotes: "Keep the pacing direct and creator-native; avoid long setup or generic face-only intros.",
    avoid: ["do not copy a reference video because none was provided"]
  };
}

function assetProfileWarnings(label: string, profile: AssetProfile): string[] {
  const warnings = [
    `Asset builder: ${label} asset ${profile.id} prepared via ${profile.analysisProvider}.`
  ];

  for (const warning of profile.qualityWarnings) {
    warnings.push(`Asset builder: ${label} warning - ${warning}`);
  }

  return warnings;
}

function firstFile(form: FormData, names: string[]): File | undefined {
  for (const name of names) {
    const value = form.get(name);
    if (value instanceof File && value.size > 0) {
      return value;
    }
  }

  return undefined;
}

async function persistRemoteVideo(
  jobId: string,
  index: number,
  videoUrl: string,
  label: string,
  warnings: string[]
): Promise<string | undefined> {
  if (!videoUrl.startsWith("http")) {
    return videoUrl;
  }

  try {
    const response = await fetch(videoUrl);

    if (!response.ok) {
      throw new Error(`HTTP ${response.status}`);
    }

    const contentType = response.headers.get("content-type") || "video/mp4";
    const bytes = Buffer.from(await response.arrayBuffer());
    const saved = await saveOutputBuffer(bytes, jobId, `${label}-${index}.mp4`);

    warnings.push(`Video cached locally for browser playback: ${saved.localUrl}`);

    if (!contentType.includes("video") && !contentType.includes("octet-stream")) {
      warnings.push(`Video cache warning: remote content-type was ${contentType}.`);
    }

    return saved.localUrl;
  } catch (error) {
    warnings.push(
      `Video cache warning: could not cache ${label} video locally (${error instanceof Error ? error.message : "unknown error"}). Using remote URL fallback.`
    );
    return undefined;
  }
}

function dedupe(values: string[]): string[] {
  return Array.from(new Set(values));
}

function mimeTypeFromPath(filePath: string): string {
  const extension = path.extname(filePath).toLowerCase();
  if (extension === ".png") return "image/png";
  if (extension === ".webp") return "image/webp";
  return "image/jpeg";
}

async function writePipelineResult(payload: PipelineResult): Promise<void> {
  await mkdir(logsDir, { recursive: true });
  const bytes = Buffer.from(JSON.stringify(payload, null, 2));
  await writeFile(
    path.join(logsDir, `pipeline-result-${payload.jobId}.json`),
    bytes,
    "utf8"
  );

  if (hasR2Config()) {
    await uploadPublicObject(
      publicObjectKey(payload.jobId, `pipeline-result-${payload.jobId}.json`),
      bytes,
      "application/json"
    );
  }
}

async function writeHistoryEntry(entry: ProjectHistoryEntry): Promise<void> {
  await mkdir(logsDir, { recursive: true });

  let previous: ProjectHistoryEntry[] = [];

  try {
    const remoteHistory = await readPublicObject(publicGlobalObjectKey("history-index.json"));
    previous = JSON.parse(remoteHistory?.toString("utf8") ?? await readFile(historyIndexPath, "utf8")) as ProjectHistoryEntry[];
  } catch {
    previous = [];
  }

  const next = [entry, ...previous.filter((item) => item.jobId !== entry.jobId)].slice(0, 100);
  const bytes = Buffer.from(JSON.stringify(next, null, 2));
  await writeFile(historyIndexPath, bytes, "utf8");

  if (hasR2Config()) {
    await uploadPublicObject(
      publicGlobalObjectKey("history-index.json"),
      bytes,
      "application/json"
    );
  }
}

async function readPipelineResult(jobId: string): Promise<PipelineResult | undefined> {
  try {
    const remote = await readPublicObject(publicObjectKey(jobId, `pipeline-result-${jobId}.json`));
    if (remote) return JSON.parse(remote.toString("utf8")) as PipelineResult;

    const raw = await readFile(path.join(logsDir, `pipeline-result-${jobId}.json`), "utf8");
    return JSON.parse(raw) as PipelineResult;
  } catch {
    return reconstructCompletedResult(jobId);
  }
}

async function reconstructCompletedResult(jobId: string): Promise<PipelineResult | undefined> {
  let outputNames: string[];

  try {
    outputNames = await readdir(outputDir);
  } catch {
    return undefined;
  }

  const videos = outputNames
    .map((name) => {
      const match = name.match(new RegExp(`^${jobId}-fal-kling-(\\d+)\\.mp4$`));
      return match ? { name, index: Number(match[1]) } : undefined;
    })
    .filter((item): item is { name: string; index: number } => Boolean(item))
    .sort((a, b) => a.index - b.index)
    .map<GeneratedVideo>((item) => ({
      index: item.index,
      hook: "Recovered completed generation",
      script: "",
      generationPrompt: "",
      playbackUrl: `/outputs/${item.name}`,
      sourceUrl: `/outputs/${item.name}`,
      audioMode: "native_audio",
      status: "completed"
    }));

  if (!videos.length) {
    return undefined;
  }

  return {
    jobId,
    analysis: {
      format: "ugc_beauty_product"
    },
    videos,
    warnings: [
      "Recovered from local output cache after the browser request disconnected.",
      "Detailed analysis/prompt data was not available for this older job because result persistence was added after it ran."
    ]
  };
}
